apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: qa_metrics
    user: admin
    password: password123
    jsonData:
      version: Flux
      organization: ares_corp
      defaultBucket: qa_metrics
      tlsSkipVerify: true
    secureJsonData:
      token: ares-super-secret-token-change-in-production
    isDefault: true
    editable: true
